### ISSUE TITLE
REM went blank

### ISSUE THREAD

**Issue by DrJeff** [rstrouse/relayEquipmentManager#11]
Lost rem configuration is it pulling from a new location? My setup is blank slate? tried a git pull but still blank, I knew that shouldn't make a difference but why not.
here is my config
```
pi@rem:~/rem/data $ cat controllerConfig.json
{
  "controllerType": "raspi",
  "gpio": {
    "pins": [],
    "exported": []
  },
  "spi0": {
    "isActive": false,
    "busNumber": 0,
    "channels": [],
    "referenceVoltage": 3.3,
    "spiClock": 1000
  },
  "spi1": {
    "isActive": false,
    "busNumber": 1,
    "channels": [],
    "referenceVoltage": 3.3,
    "spiClock": 1000
  },
  "i2c": {
    "isActive": false,
    "buses": [],
    "detected": [
      {
        "driver": "bcm2835 (i2c@7e804000)",
        "path": "/sys/class/i2c-dev/i2c-1",
        "name": "i2c-1",
        "busNumber": 1
      }
    ]
  },
  "connections": [
    {
      "id": 1,
      "isActive": true,
      "options": {},
      "name": "njsPC - automatic",
      "type": "njspc",
      "protocol": "http:",
      "ipAddress": "192.168.0.179",
      "port": 4200,
      "userName": "",
      "password": "",
      "sslKeyFile": "",
      "sslCertFile": ""
    }
  ],
  "genericDevices": {
    "isActive": true,
    "buses": [],
    "detected": [],
    "options": {},
    "devices": []
  },
  "lastUpdated": "6/7/2021, 12:41:09 AM",
  "configVersion": 1
```
But my setup is gone
![Screen Shot 2021-06-07 at 12 51 57 AM](https://user-images.githubusercontent.com/1709631/120979656-abcfac80-c72a-11eb-847d-b4d23ac614ac.png)
![Screen Shot 2021-06-07 at 12 52 10 AM](https://user-images.githubusercontent.com/1709631/120979660-ad00d980-c72a-11eb-9215-31828c3f038f.png)
![Screen Shot 2021-06-07 at 12 52 03 AM](https://user-images.githubusercontent.com/1709631/120979662-ad997000-c72a-11eb-9db7-46025818c7bf.png)

**Comment by rstrouse** [comment]
Add the I2c bus back in.

**Comment by DrJeff** [comment]
? was never removed, just lost dhcp address and after reboot I got the above

**Comment by rstrouse** [comment]
There isn’t a check in there for net connections that would remove the I2c bus definition.  It almost looks like there was a load error on startup.  Perhaps I need to force the persistence to off if there is something catastrophic on load.  I’ll harden that up so it won’t persist if the server doesn’t completely come up.

**Comment by DrJeff** [comment]
Whats the best plan of action for me, just add all my stuff again?

**Comment by rstrouse** [comment]
Yes then back up the file.  I will dig through this but the only path I can see for this to happen is that the file load on startup failed without throwing an error.  Maybe it ended up being locked or the file ownership changed.
