### ISSUE TITLE
FEATURE REQUEST: d18b20 temp sensor over 1wire

### ISSUE THREAD

**Issue by johnny2678** [rstrouse/relayEquipmentManager#2]
Just logging this as a wish list item.  I wish I could help with the code but I do have these connected to my pi right now.  Currently using python to grab values.  

Happy to help test if you guys want to take a stab at adding support at some point.

**Comment by DrJeff** [comment]
I want it but gotta install REM first :), I'm using d18b20 currently on my other setup

**Comment by DrJeff** [comment]
any update on ds18B20 temp sensor working?

**Comment by tagyoureit** [comment]
Not yet... thanks for the reminder.

**Comment by tagyoureit** [comment]
I ordered a DS18b20 so I'll work on getting this hooked up and then verify by next week.

**Comment by tagyoureit** [comment]
Pull down REM 7.5.0.  1-wire + DS18B20 added.

**Comment by rstrouse** [comment]
This feature has been added.  Open another issue if you find any problems.
