### ISSUE TITLE
Issue setting up valves

### ISSUE THREAD

**Issue by Exit2Studios** [rstrouse/relayEquipmentManager#21]
I have njspc and rem working on an Rpi4 combined with a Sequent Microsystems BAS and 8-relay IND board..  I'm using a single standard valve for testing and have it assigned as my intake valve on a shared body nixie controller.  However, when I switch from pool/spa the valve does not activate.  I can control it via the Sequent Microsystems command line prompt.

**Comment by rstrouse** [comment]
So it sounds like you have the valve wired properly.  Shoot me a screenshot of the I2c page.  It should looks something like this when you select the Multi-Relay Board.
![image](https://user-images.githubusercontent.com/47839015/131383624-5f8a3729-3056-4b8e-b99a-0c16c5d978c8.png)

**Comment by Exit2Studios** [comment]
Here are the screenshots:


    On Monday, August 30, 2021, 12:59:40 PM CDT, rstrouse ***@***.***> wrote:  
 
 


So it sounds like you have the valve wired properly. Shoot me a screenshot of the I2c page. It should looks something like this when you select the Multi-Relay Board.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rstrouse** [comment]
The screenshots didn't come through

**Comment by Exit2Studios** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/16908875/131389032-7fd097f2-bb24-4fae-bf7f-13ea8239eeac.png">

**Comment by rstrouse** [comment]
Ok so delete that trigger.  You do not want that trigger set up for a Nixie controller.  The connection is more direct that when using Nixie and it does some work to make sure relays reflect the desired state of the pool.  This is done through relay latching from njsPC.  To configure an Intake valve simply navigate to the valves tab in dashPanel and set it up like you have above.
![image](https://user-images.githubusercontent.com/47839015/131389148-84866f0c-5899-4420-9484-17f07ec70570.png)

Show me a screenshot just like the first one I posted.

**Comment by rstrouse** [comment]
Ok so I just now saw the screenshot.  You do not have the correct address for the Relay board.  It is not at address 3 (0x03) it is at address 63 (0x3F) if you did not change any of the jumpers on the card.

**Comment by rstrouse** [comment]
Delete the Multi-Relay Board from REM and if it does not automatically detect the relay, then hit the + and use 63 as the address.  You can hit the Re-scan button to have it scan for addresses but it is possible that the address might not show up on the scan.  Especially if there is other software hitting the device.  Such is the nature of I2c.

**Comment by Exit2Studios** [comment]
That seems to have done the trick.  I knew it had to be user error.  Thank you!

**Comment by rstrouse** [comment]
Yeah for the world of me I couldn't see a path where it wouldn't be working.  Sometimes a picture is worth a thousand words.
