### ISSUE TITLE
Cannot feed 10k BAS Temp Probe to Generic Device

### ISSUE THREAD

**Issue by ddyer8** [rstrouse/relayEquipmentManager#30]
Copy-paste from Gitter discussion:

I'm in the process of initial configuration of a DIY-Standalone-Nixie-Pool-Controller with REM, and I cannot get the 10k BAS Temp Probe to feed the Generic Device. I have nodejs-poolController, dash Panel, and REM up and running on a pi4 with Sequent MEGA-BAS. I have 10k temp probe hooked up to AI 1. I have followed the instructions on the wiki a few times (https://github.com/rstrouse/relayEquipmentManager/wiki/Sequent-Microsystems-Boards#sequent-building-automation-hat-mega-bas) and the generic device will not retain the settings to be fed by the BAS. Usually, the Generic Device configuration screen lacks the Save and Delete Device buttons. Have you seen this behavior before? Recommended troubleshooting steps?

Initial configuration of the Generic Devices screen:
![image](https://user-images.githubusercontent.com/10640913/161176345-45ae3b86-fb48-4f76-a40b-bcc6b7e2ec38.png)

Configuration of the MEGA-BAS Feed:
![image](https://user-images.githubusercontent.com/10640913/161176409-72870f64-1bf9-429a-a7e1-6f7cc0b80205.png)

Image of Generic Devices probe after configuring MEGA-BAS Feed:
![image](https://user-images.githubusercontent.com/10640913/161176186-05bd8f07-bf68-48f7-8c04-f9cdabba3ddb.png)

**Comment by rstrouse** [comment]
Change the send value on the MEGA-BAS feed from the `0-10v in #1` to `0-10v in #1 value`.  You are currently feeding the entire object reference to the generic device.   The temperature probe device only knows how to process the raw numeric value from the input.
![image](https://user-images.githubusercontent.com/47839015/161177332-1f0852f1-627a-45e2-ba31-058ee6cefbcc.png)

**Comment by ddyer8** [comment]
Shoot.  I see now the instructions clearly say to pick the one with "value." Works fine for me now.

Any way for the Generic Object to generate a warning or error when fed the object and expecting a value?  If so, perhaps this would be a good enhancement? Either way, I'm fine closing the issue.

**Comment by rstrouse** [comment]
I just need to do some work on the UI but I have other priorities right now.

**Comment by rstrouse** [comment]
Closing
