### ISSUE TITLE
No interpreting Ohms as Temp

### ISSUE THREAD

**Issue by LTrainExpress** [rstrouse/relayEquipmentManager#32]
I have a 10k probe connected to the Sequent board. My WaterTemp device is getting the Ohm value, but not converting it to Temp. Any idea why? Not sure if this is an issue or just a question.

![image](https://user-images.githubusercontent.com/15890941/172010434-25c61068-47af-4a81-89e2-ec2c11de2e87.png)

**Comment by rstrouse** [comment]
Closing this as I assume you got this all set up correctly.
