### ISSUE TITLE
Uncaught ReferenceError: o is not defined - when clicking between i2c devices

### ISSUE THREAD

**Issue by johnny2678** [rstrouse/relayEquipmentManager#33]
Didn't notice this on my old distributed install but getting this error on my new, single pi stack.

Not sure if this is a user error or something in the code but wanted to make you aware.

steps to reproduce:
1. Open REM
2. click the i2c tab
3. click an i2c device - device config will load
4. click on a different i2c device - nothing happens (device config does not load) and uncaught reference error in chrome console

![image](https://user-images.githubusercontent.com/8219743/174831052-4c5cc8d9-d369-4940-974e-6bd659bb6e62.png)

Easy fix, just refresh the chrome tab and navigate to the i2c device you want to view.

**Comment by tagyoureit** [comment]
I can't replicate this.  Something might be corrupt with your config.  Can you upload the `./data/controllerConfig.json` and we'll see if we can figure it out?

**Comment by johnny2678** [comment]
sure thing... 
[controllerConfig.txt](https://github.com/rstrouse/relayEquipmentManager/files/8966822/controllerConfig.txt)

**Comment by tagyoureit** [comment]
First, you watchdog script...
```
if (values.batteryVolts < 3.45 && values.sourceVolts < 2){
    exec('sudo shutdown --halt --poweroff; pm2 stop all;', (error, stdout, stderr) => {
      if (error !== null) return error;
      if (stderr !== '') return stderr;
    return stdout;
    })
}

return `OK: ${new Date().toLocaleString()}|JH`;
```
is telling the Pi to shutdown and then stop pm2 processes.  Those should be reversed.  :)

Second, pull REM.  I found the issue.

**Comment by johnny2678** [comment]
pretty sure you wrote that line 😂

it's the same line from the [wiki](https://github.com/rstrouse/relayEquipmentManager/wiki/Sequent-Microsystems-Boards#settings-1)

And i thought the same thing when I first used it but one of the flags (`--halt` or `--poweroff`) actually delays the shutdown for 1 minute, so the `pm2` cmds do complete

pulled the latest and clicked through all my i2c devices with no issues.  I think you nailed this one!  Will close and reopen if I see anything else. thx!
