### ISSUE TITLE
Add Connection, Server Name Limited to 20 Characters

### ISSUE THREAD

**Issue by arrmo** [rstrouse/relayEquipmentManager#37]
Minor, but ... when trying to add a new connection, the server name field is limited to 20 characters => can be an issue when putting in the FQDN. BTW, if auto-detecting the connection, more than 20 characters is allowed.

Thanks!

**Comment by rstrouse** [comment]
Yep a little short sighted.  You will need to hard refresh your browser for the change to take effect.

**Comment by arrmo** [comment]
Minor, no worries. Thanks!
