### ISSUE TITLE
MCP3008 ADC question

### ISSUE THREAD

**Issue by thrystan** [rstrouse/relayEquipmentManager#44]
My MCP3008 chip is not being recognized, how to I specify which GPIO pin is connected to the cs pin on the chip?

**Comment by rstrouse** [comment]
Are you using SPI?  If it were me I would abandon that and go with an I2c chip like ADS10x5.  There is so much better support on the I2c side.  SPI wile you can get it to talk it can be a pain to work through all the connections.

**Comment by thrystan** [comment]
Yes I'm using the MCP3008 SPI chip, it has been working great with the code I've been using, but I can't get it to work with REM, and after I started using REM it quit responding to my code that had been working. My thought is that REM is doing something to block the GPIO pin that is used for the chip select pin on the MCP3008.

**Comment by rstrouse** [comment]
Disable the SPI bus by unchecking it on the General tab then reload the server.

**Comment by thrystan** [comment]
Ok, thank you.

**Comment by rstrouse** [comment]
Pull REM.  I improved the SPI interface to allow devices to be better defined.
