### ISSUE TITLE
Updating REM and poolController

### ISSUE THREAD

**Issue by bruno-monk** [rstrouse/relayEquipmentManager#48]
Is there a published update/upgrade procedure for both of these components?

**Comment by bruno-monk** [comment]
Found it: 
Change directory to the njsPC app
git pull
npm i (not always necessary, but if dependencies are upgraded this will bring them up to date)
Start application as normal, or if using npm run start:cached then run npm run build to compile the code.

**Comment by tagyoureit** [comment]
There is a nice upgrade script at https://github.com/tagyoureit/nodejs-poolController/discussions/496 that will upgrade all three projects automatically.
