### ISSUE TITLE
Support for Pimoroni Automation HAT

### ISSUE THREAD

**Issue by marthoc** [rstrouse/relayEquipmentManager#70]
I see in the wiki that the ADCs on [this board](https://shop.pimoroni.com/products/automation-hat?variant=30712316554) are supported for e.g. temperature probes. Are the rest of the inputs/outputs on that HAT supported also (e.g. relays, 24v inputs/outputs)? I have a simple pool setup (single body, one VS pump, one heater, one filter, Aquarite LS SWG) and if I can accomplish most of what I want to do with that relatively inexpensive HAT and an RS485 usb, that would be ideal.

Thanks for all of your work on this solution!

**Comment by marthoc** [comment]
I think I have answered my own question - it appears that the inputs/outputs and relays are tied to GPIO pins: 
![image](https://github.com/rstrouse/relayEquipmentManager/assets/30442019/ea664998-45d9-4502-90fa-10f7546946b1)
So, given that REM can control the RPi status of the relay PINs, I would assume that it can control these?

**Comment by rstrouse** [comment]
That is correct.  The ADC is actually an ADS 1x15 and there is a Pimoroni setting in there for that.

**Comment by marthoc** [comment]
@rstrouse Thanks for confirming!
