### ISSUE TITLE
Cannot save Alarm Low and Alarm High settings in Fahrenheit  for new one-wire temperature probe

### ISSUE THREAD

**Issue by dkossman** [rstrouse/relayEquipmentManager#82]
Minor issue because there is a workaround.  

steps to reproduce
1. add new DS18B20 1-wire probes (e.g. for Pool, Spa or Air temp)
2. select Device Options, 
3. select F units in the pulldown 
4.  update Alarm Low to e.g. 50 degrees F
5. update Alarm High to 103 degrees F
6. click Save Device

expected - values are saved
actual - values are changed to 131 and 127

Notes: 
1. if you select Centigrade, everything works as expected
2. after setting alarms in Centigrade, if you switch the units to F and hit Save, the values are converted and saved

**Comment by tagyoureit** [comment]
Fixed this.  But, the alarms don't do anything in the app.
